services:
  keycloak-postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - demo-network

  keycloak:
    # image: jboss/keycloak
    image: ${DOCKER_REGISTRY-}keycloakauth
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8181:8080
    command: -v start-dev --import-realm
    depends_on:
      - keycloak-postgres
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_VENDOR: postgres
      KC_JDBC_PARAMS: "connectTimeout=30"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    networks:
      - demo-network

networks:
  demo-network:
    driver: bridge
